language: node_js
node_js:
  - 4.1
env:
  global:
    - GH_REF: github.com/ptsurko/vr-protos.git
    - GIT_NAME: Travis-CI
    - GIT_EMAIL: travis@nodemeatspace.com
    - secure: O7/28oDpohW12bT1ljECocCTl4Ka6WKuXTUNHqZVbRWrS8pHqKlusdATaoBsVguOq5ww857QiBgHmVyGfeopvXVoahf9sAE3Cw7FYSS5ordkPqWH0pSPDB/iOGEALW/ptNXDGIhOzQHJcbWUABWEEN77Jn0ST67DJqX42zKDe/HOAt5xFU/TpAjyOonaOBmwPK4IyQiH1jVk/W1Lh2R3VEsa37u9Kne9hpKZ6vbzKT+Yc10aRqiERrhfPDquc+aX1VHAwbXSqRfkdocAfN2cgxQsoA7Sei4tMijAyNbZwByig27inVxjAJxWqi9bPaPtgLUc+BgV0k5n8geAL6xWVVtd2QJYm1od/cI8pcFFuZSohajR+HkgLcuSwS/6euST+WI697PoBigoVFiwSEA1pz/OhFl1K1hWoQj6WyGY0ji/JvpCBjmVLdytYerRgdwHtsivge1TihTRCG+xSl3c76ssIps4iD9ObpmQjbMMw/L2KPVM4BC37Yo5ZOGAtg0AfET4E6Pdv2opWYJsO98fJSIuaeWORrY4Rr1sng9yzEsHYesi5sz1RrOY3UcSux1c2aN5s/JB4VZpXfSpkgo7G8jZJ8SxROunEwK1rPf2Hbyxea0tUvupt1n9nnuZnJK4U9UIxTj67cZaDSFfKOCXzvf5zUzVcPSgEAm+asjXsG8=
before_install:
  - chmod +x deploy_ghpages.sh
before_script:
  - npm install
  - npm install -g bower
  - bower install
script: bash ./deploy_ghpages.sh
branches:
  only:
    - master
